eureka:
  client:
    serviceUrl:
      defaultZone: http://leaf:leaf@localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: service-provider-demo
  datasource:
    name: taotao
    url: jdbc:mysql://localhost:3306/taotao
    username: root
    password: leaf
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    #validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.gs.serviceproviderdemo.model
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql