eureka:
  client:
    serviceUrl:
      defaultZone: http://leaf:leaf@localhost:8761/eureka/
server:
  port: 8771
spring:
  application:
    name: service-cumtomer-demo

feign:
  hystrix:
    enabled: true
logging:
  level:
    com.gs.serviceproviderdemo.service.FeignClientDemo: DEBUG
