
spring:
  thymeleaf:
    cache: false
    content-type: text/html
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  devtools:
    restart:
      enabled: true
  freemarker:
    template-loader-path: classpath:/templates/
    cache: false
    check-template-location: true
    charset: UTF-8
    suffix: .ftl
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/taotao
    username: root
    password: leaf
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8088
  session:
    timeout: 60
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8
mybatis:
  type-aliases-package: com.gs.leaf.pojo
  mapper-locations: classpath:mapper/*.xml

