eureka:
  client:
    serviceUrl:
      defaultZone: http://leaf:leaf@localhost:8761/eureka/
server:
  port: 8770
spring:
  application:
    name: service-cumtomer-demo

feign:
  hystrix:
    enabled: true
